# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'job_table_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_list_jobs(object):
    def setupUi(self, Form_list_jobs):
        Form_list_jobs.setObjectName("Form_list_jobs")
        Form_list_jobs.setWindowModality(QtCore.Qt.ApplicationModal)
        Form_list_jobs.resize(570, 519)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form_list_jobs)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_filter_column = QtWidgets.QLabel(Form_list_jobs)
        self.lbl_filter_column.setObjectName("lbl_filter_column")
        self.horizontalLayout.addWidget(self.lbl_filter_column)
        self.cb_column = QtWidgets.QComboBox(Form_list_jobs)
        self.cb_column.setObjectName("cb_column")
        self.horizontalLayout.addWidget(self.cb_column)
        self.label = QtWidgets.QLabel(Form_list_jobs)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_filter = QtWidgets.QLineEdit(Form_list_jobs)
        self.le_filter.setObjectName("le_filter")
        self.horizontalLayout.addWidget(self.le_filter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tv_all_jobs = QtWidgets.QTableView(Form_list_jobs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(18)
        sizePolicy.setVerticalStretch(18)
        sizePolicy.setHeightForWidth(self.tv_all_jobs.sizePolicy().hasHeightForWidth())
        self.tv_all_jobs.setSizePolicy(sizePolicy)
        self.tv_all_jobs.setSizeIncrement(QtCore.QSize(0, 0))
        self.tv_all_jobs.setBaseSize(QtCore.QSize(444, 444))
        self.tv_all_jobs.setAutoFillBackground(True)
        self.tv_all_jobs.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tv_all_jobs.setSortingEnabled(True)
        self.tv_all_jobs.setObjectName("tv_all_jobs")
        self.verticalLayout.addWidget(self.tv_all_jobs)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 20)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form_list_jobs)
        QtCore.QMetaObject.connectSlotsByName(Form_list_jobs)

    def retranslateUi(self, Form_list_jobs):
        _translate = QtCore.QCoreApplication.translate
        Form_list_jobs.setWindowTitle(_translate("Form_list_jobs", "LIst of jobs advertisement"))
        self.lbl_filter_column.setText(_translate("Form_list_jobs", "Филтър по колона"))
        self.label.setText(_translate("Form_list_jobs", "текст за търсене:"))
