# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'job_table_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_list_jobs(object):
    def setupUi(self, Form_list_jobs):
        Form_list_jobs.setObjectName("Form_list_jobs")
        Form_list_jobs.resize(515, 453)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form_list_jobs)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 501, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_filter = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_filter.setObjectName("lbl_filter")
        self.horizontalLayout.addWidget(self.lbl_filter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_filter_column = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_filter_column.setObjectName("lbl_filter_column")
        self.horizontalLayout.addWidget(self.lbl_filter_column)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.de_post_date = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.de_post_date.setObjectName("de_post_date")
        self.horizontalLayout_2.addWidget(self.de_post_date)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.cb_column = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cb_column.setObjectName("cb_column")
        self.horizontalLayout_2.addWidget(self.cb_column)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tv_all_jobs = QtWidgets.QTableView(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(18)
        sizePolicy.setVerticalStretch(18)
        sizePolicy.setHeightForWidth(self.tv_all_jobs.sizePolicy().hasHeightForWidth())
        self.tv_all_jobs.setSizePolicy(sizePolicy)
        self.tv_all_jobs.setBaseSize(QtCore.QSize(444, 444))
        self.tv_all_jobs.setSortingEnabled(True)
        self.tv_all_jobs.setObjectName("tv_all_jobs")
        self.verticalLayout.addWidget(self.tv_all_jobs)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 20)
        self.btn_close = QtWidgets.QPushButton(Form_list_jobs)
        self.btn_close.setGeometry(QtCore.QRect(400, 420, 111, 31))
        self.btn_close.setObjectName("btn_close")

        self.retranslateUi(Form_list_jobs)
        QtCore.QMetaObject.connectSlotsByName(Form_list_jobs)

    def retranslateUi(self, Form_list_jobs):
        _translate = QtCore.QCoreApplication.translate
        Form_list_jobs.setWindowTitle(_translate("Form_list_jobs", "LIst of jobs advertisement"))
        self.lbl_filter.setText(_translate("Form_list_jobs", "Филтър по дата:"))
        self.lbl_filter_column.setText(_translate("Form_list_jobs", "Филтър по колона"))
        self.btn_close.setText(_translate("Form_list_jobs", "Изход"))
