# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'job_crawler_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(562, 205)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 531, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_load_all = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_load_all.setObjectName("btn_load_all")
        self.gridLayout.addWidget(self.btn_load_all, 1, 0, 1, 1)
        self.btn_read_site = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_read_site.setObjectName("btn_read_site")
        self.gridLayout.addWidget(self.btn_read_site, 0, 0, 1, 1)
        self.lbl_last_readed = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_last_readed.setObjectName("lbl_last_readed")
        self.gridLayout.addWidget(self.lbl_last_readed, 0, 1, 1, 1)
        self.lbl_info_in_db = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_info_in_db.setObjectName("lbl_info_in_db")
        self.gridLayout.addWidget(self.lbl_info_in_db, 1, 1, 1, 1)
        self.btn_close = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_close.setObjectName("btn_close")
        self.gridLayout.addWidget(self.btn_close, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_load_all.setText(_translate("Form", "Зареди данните от таблицата"))
        self.btn_read_site.setText(_translate("Form", "Прочети данните от сайта"))
        self.lbl_last_readed.setText(_translate("Form", "Последно прочитане на: "))
        self.lbl_info_in_db.setText(_translate("Form", "Налични данни в таблицата :"))
        self.btn_close.setText(_translate("Form", "Изход"))
