# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'job_crawler_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(210, 140)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 191, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Btn_read_site = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_read_site.setObjectName("Btn_read_site")
        self.verticalLayout.addWidget(self.Btn_read_site)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Btn_load_all = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_load_all.setObjectName("Btn_load_all")
        self.verticalLayout.addWidget(self.Btn_load_all)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.Btn_close = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_close.setObjectName("Btn_close")
        self.verticalLayout.addWidget(self.Btn_close)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Btn_read_site.setText(_translate("Form", "Прочети данните от сайта"))
        self.Btn_load_all.setText(_translate("Form", "Зареди данните от таблицата"))
        self.Btn_close.setText(_translate("Form", "Изход"))
